const ejemplo = [

    {
        nombre : 'CHRIS',
        fecha : '10-02-2003',
        telefono : '9921040022',
        correo : 'chris@gmail.com',
        direccion : '1ra Calle Sur Poniente',
        rfc : 'XAXX010101AA',
        curp : 'MOMC020615HCSSA3',
        estadoCivil : 'Soltero',
        nombreParentesco : 'Santiago De Jesus',
        parentesco : 'Padre',
        telefonoParentesco : '9921055055',
        direccionParentesco : '1ra Calle Sur Poniente',
        nombreEmpresa : 'Saltillo, San Cristobal',
        puesto : 'Gerente',
        telefonoEmpresa : '7894561230',
        direccionEmpresa : 'Saltillo, San Cristobal',
        buro : 'no',
        creditoActual : 'si',
        monto : '92000',
        credito : 'si',
        debito : 'no',
        cuentaBancaria : 'Banco Azteca'
    },{
        nombre : 'JORDI',
        fecha : '10-02-2003',
        telefono : '9921040022',
        correo : 'jordi@gmail.com',
        direccion : '1ra Calle Sur Poniente',
        rfc : 'XAXX010101AAA07072016_01',
        curp : 'MOMC0SA3',
        estadoCivil : 'Soltero',
        nombreParentesco : 'Santiago De Jesus',
        parentesco : 'Padre',
        telefonoParentesco : '9921055055',
        direccionParentesco : '1ra Calle Sur Poniente',
        nombreEmpresa : 'Saltillo, San Cristobal',
        puesto : 'Gerente',
        telefonoEmpresa : '7894561230',
        direccionEmpresa : 'Saltillo, San Cristobal',
        buro : 'no',
        creditoActual : 'no',
        monto : '92000',
        credito : 'si',
        debito : 'no',
        cuentaBancaria : 'Banco Azteca'
    },{
        nombre : 'GABRIEL',
        fecha : '10-02-2003',
        telefono : '9921040022',
        correo : 'Gabi@gmail.com',
        direccion : '1ra Calle Sur Poniente',
        rfc : 'AA07072016_01',
        curp : 'C0215HCSSA3',
        estadoCivil : 'Soltero',
        nombreParentesco : 'Santiago De Jesus',
        parentesco : 'Padre',
        telefonoParentesco : '9921055055',
        direccionParentesco : '1ra Calle Sur Poniente',
        nombreEmpresa : 'Saltillo, San Cristobal',
        puesto : 'Gestor',
        telefonoEmpresa : '7894561230',
        direccionEmpresa : 'Saltillo, San Cristobal',
        buro : 'no',
        creditoActual : 'si',
        monto : '92000',
        credito : 'si',
        debito : 'no',
        cuentaBancaria : 'Banco Azteca'
    }  

];

export default ejemplo;